// 00.references/user/userModal.tsx
import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { User, Lock, Eye, EyeOff } from "lucide-react";
import { getTranslation, type LocaleCode } from "@/lib/i18n";

interface UserModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  userName: string;
  userEmail: string;
  language?: LocaleCode;
}

export const UserModal = ({ open, onOpenChange, userName, userEmail, language = "en" }: UserModalProps) => {
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);

  const handleSignIn = () => {
    if (password) {
      console.log(`Signing in as ${userName} with password: ${password}`);
      // Handle sign in logic here
      onOpenChange(false);
      // Reset form
      setPassword("");
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-full max-w-sm bg-card rounded-2xl shadow-login-panel overflow-hidden p-0">
        {/* Blue Header Section */}
        <div className="bg-primary px-8 py-8 text-center">
          <div className="w-16 h-16 bg-white/20 rounded-full mx-auto mb-4 flex items-center justify-center overflow-hidden">
            <User className="w-8 h-8 text-white" />
          </div>
          <DialogHeader className="sm:text-center">
            <DialogTitle className="text-2xl font-light text-white">{userName}</DialogTitle>
          </DialogHeader>
          <p className="text-white/80 mt-1 font-light">{userEmail}</p>
        </div>

        {/* White Content Section */}
        <div className="px-8 py-6 space-y-4">
          {/* Password */}
          <div className="space-y-2">
            <Label htmlFor="password" className="text-sm font-medium">{getTranslation(language, "password")}</Label>
            <div className="relative">
              <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                id="password"
                type={showPassword ? "text" : "password"}
                placeholder={getTranslation(language, "password")}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full bg-input border-border text-card-foreground placeholder:text-muted-foreground rounded h-10 pl-10 pr-10 focus:border-primary focus:ring-primary/30 transition-all duration-200"
                onKeyDown={(e) => e.key === "Enter" && handleSignIn()}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 transform -translate-y-1/2 text-muted-foreground hover:text-card-foreground transition-colors"
              >
                {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
          </div>

          <Button
            onClick={handleSignIn}
            disabled={!password}
            className="w-full bg-primary hover:bg-primary-glow text-primary-foreground font-medium rounded h-10 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {getTranslation(language, "signIn")}
          </Button>

          {/* Footer Links */}
          <div className="mt-6 text-center">
            <button className="text-primary hover:underline text-sm font-medium">
              {getTranslation(language, "forgotPassword")}
            </button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default UserModal;

// src/components/authentication/user/UserModal.vue
<template>
  <Teleport to="body">
    <Transition name="modal">
      <div v-if="open" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" @click.self="closeModal">
        <div class="w-full max-w-sm bg-white rounded-2xl shadow-xl overflow-hidden">
          <!-- Blue Header Section -->
          <div class="bg-blue-600 px-8 py-8 text-center">
            <div class="w-16 h-16 bg-white/20 rounded-full mx-auto mb-4 flex items-center justify-center overflow-hidden">
              <User :size="32" class="text-white" />
            </div>
            <h2 class="text-2xl font-light text-white">{{ userName }}</h2>
            <p class="text-white/80 mt-1 font-light">{{ userEmail }}</p>
          </div>

          <!-- White Content Section -->
          <div class="px-8 py-6 space-y-4">
            <!-- Password -->
            <div class="space-y-2">
              <label for="password" class="text-sm font-medium text-gray-700">{{ t('password') }}</label>
              <div class="relative">
                <Lock :size="16" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <input
                  id="password"
                  ref="passwordInput"
                  :type="showPassword ? 'text' : 'password'"
                  :placeholder="t('password')"
                  v-model="password"
                  @keyup.enter="handleSignIn"
                  class="w-full bg-gray-50 border border-gray-300 text-gray-900 rounded h-10 pl-10 pr-10 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/30 transition-all duration-200 outline-none"
                />
                <button
                  type="button"
                  @click="showPassword = !showPassword"
                  class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                >
                  <EyeOff v-if="showPassword" :size="16" />
                  <Eye v-else :size="16" />
                </button>
              </div>
            </div>

            <button
              @click="handleSignIn"
              :disabled="!password"
              class="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium rounded h-10 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {{ t('signIn') }}
            </button>

            <!-- Footer Links -->
            <div class="mt-6 text-center">
              <button class="text-blue-600 hover:underline text-sm font-medium">
                {{ t('forgotPassword') }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, watch, nextTick } from 'vue'
import { User, Lock, Eye, EyeOff } from 'lucide-vue-next'
import { useI18n } from '@/composables/useI18n'
import { useAuth } from '@/composables/useAuth'

const props = defineProps<{
  open: boolean
  userName: string
  userEmail: string
}>()

const emit = defineEmits<{
  'update:open': [value: boolean]
}>()

const { t } = useI18n()
const { login, mockUsers } = useAuth()

const password = ref('')
const showPassword = ref(false)
const passwordInput = ref<HTMLInputElement | null>(null)

const closeModal = () => {
  emit('update:open', false)
  password.value = ''
  showPassword.value = false
}

const handleSignIn = () => {
  if (password.value) {
    console.log(`Signing in as ${props.userName} with password: ${password.value}`)
    const user = mockUsers.find(u => u.name === props.userName)
    if (user) {
      login(user)
    }
    closeModal()
  }
}

// Focus password input when modal opens
watch(() => props.open, (isOpen) => {
  if (isOpen) {
    nextTick(() => {
      passwordInput.value?.focus()
    })
  }
})
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.3s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}
</style>
