// src/components/authentication/registration/SignupModal.vue
<template>
  <Teleport to="body">
    <Transition name="modal">
      <div v-if="open" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" @click.self="closeModal">
        <div class="w-full max-w-sm bg-white rounded-2xl shadow-xl overflow-hidden">
          <!-- Blue Header Section -->
          <div class="bg-blue-600 px-8 py-8 text-center">
            <div class="w-16 h-16 bg-white/20 rounded-full mx-auto mb-4 flex items-center justify-center overflow-hidden">
              <img v-if="avatarUrl" :src="avatarUrl" alt="Avatar" class="w-16 h-16 object-cover" />
              <User v-else :size="32" class="text-white" />
            </div>
            <h2 class="text-2xl font-light text-white">{{ t('createAccount') }}</h2>
            <p class="text-white/80 mt-1 font-light">{{ t('enterDetailsToSignup') }}</p>
          </div>

          <!-- White Content Section -->
          <div class="px-8 py-6 space-y-4">
            <!-- First Name -->
            <div class="space-y-2">
              <label for="firstName" class="text-sm font-medium text-gray-700">{{ t('firstName') }}</label>
              <div class="relative">
                <User :size="16" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <input
                  id="firstName"
                  type="text"
                  :placeholder="t('firstName')"
                  v-model="firstName"
                  class="w-full bg-gray-50 border border-gray-300 text-gray-900 rounded h-10 pl-10 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/30 transition-all duration-200 outline-none"
                />
              </div>
            </div>

            <!-- Last Name -->
            <div class="space-y-2">
              <label for="lastName" class="text-sm font-medium text-gray-700">{{ t('lastName') }}</label>
              <div class="relative">
                <User :size="16" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <input
                  id="lastName"
                  type="text"
                  :placeholder="t('lastName')"
                  v-model="lastName"
                  class="w-full bg-gray-50 border border-gray-300 text-gray-900 rounded h-10 pl-10 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/30 transition-all duration-200 outline-none"
                />
              </div>
            </div>

            <!-- Email -->
            <div class="space-y-2">
              <label for="email" class="text-sm font-medium text-gray-700">{{ t('email') }}</label>
              <div class="relative">
                <Mail :size="16" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <input
                  id="email"
                  type="email"
                  :placeholder="t('emailAddress')"
                  v-model="email"
                  @input="handleEmailChange"
                  class="w-full bg-gray-50 border border-gray-300 text-gray-900 rounded h-10 pl-10 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/30 transition-all duration-200 outline-none"
                />
              </div>
            </div>

            <!-- Password -->
            <div class="space-y-2">
              <label for="password" class="text-sm font-medium text-gray-700">{{ t('password') }}</label>
              <div class="relative">
                <Lock :size="16" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <input
                  id="password"
                  :type="showPassword ? 'text' : 'password'"
                  :placeholder="t('password')"
                  v-model="password"
                  @keyup.enter="handleSignup"
                  class="w-full bg-gray-50 border border-gray-300 text-gray-900 rounded h-10 pl-10 pr-10 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/30 transition-all duration-200 outline-none"
                />
                <button
                  type="button"
                  @click="showPassword = !showPassword"
                  class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                >
                  <EyeOff v-if="showPassword" :size="16" />
                  <Eye v-else :size="16" />
                </button>
              </div>
            </div>

            <button
              @click="handleSignup"
              :disabled="!firstName || !lastName || !email || !password"
              class="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium rounded h-10 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {{ t('createAccount') }}
            </button>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { User, Mail, Lock, Eye, EyeOff } from 'lucide-vue-next'
import { useI18n } from '@/composables/useI18n'

defineProps<{
  open: boolean
}>()

const emit = defineEmits<{
  'update:open': [value: boolean]
}>()

const { t } = useI18n()

const firstName = ref('')
const lastName = ref('')
const email = ref('')
const password = ref('')
const showPassword = ref(false)
const avatarUrl = ref('')

// MD5 hash function (simple implementation for Gravatar)
const md5 = (str: string): string => {
  // This is a placeholder - in production, use a proper MD5 library
  // For now, just return a placeholder
  return str.split('').reduce((a, b) => {
    a = ((a << 5) - a) + b.charCodeAt(0)
    return a & a
  }, 0).toString(16)
}

const handleEmailChange = () => {
  const trimmed = email.value.trim().toLowerCase()
  if (trimmed && /.+@.+\..+/.test(trimmed)) {
    const hash = md5(trimmed)
    avatarUrl.value = `https://www.gravatar.com/avatar/${hash}?d=identicon`
  } else {
    avatarUrl.value = ''
  }
}

const closeModal = () => {
  emit('update:open', false)
  firstName.value = ''
  lastName.value = ''
  email.value = ''
  password.value = ''
  showPassword.value = false
  avatarUrl.value = ''
}

const handleSignup = () => {
  if (firstName.value && lastName.value && email.value && password.value) {
    console.log('Creating account:', { 
      firstName: firstName.value, 
      lastName: lastName.value, 
      email: email.value, 
      password: password.value 
    })
    closeModal()
  }
}
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.3s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}
</style>

// 00.references/from.loginStandard/src/components/accessControl/authentication/registration/signupModal.tsx
import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { User, Mail, Lock, Eye, EyeOff } from "lucide-react";
import { getTranslation, type LocaleCode } from "@/lib/i18n";
import md5 from "blueimp-md5";

interface SignupModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  language?: LocaleCode;
}

export const SignupModal = ({ open, onOpenChange, language = "en" }: SignupModalProps) => {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [avatarUrl, setAvatarUrl] = useState<string>("");

  const handleSignup = () => {
    if (firstName && lastName && email && password) {
      console.log("Creating account:", { firstName, lastName, email, password });
      // Handle signup logic here
      onOpenChange(false);
      // Reset form
      setFirstName("");
      setLastName("");
      setEmail("");
      setPassword("");
    }
  };

  const handleEmailChange = (value: string) => {
    setEmail(value);
    const trimmed = value.trim().toLowerCase();
    if (trimmed && /.+@.+\..+/.test(trimmed)) {
      const hash = md5(trimmed);
      setAvatarUrl(`https://www.gravatar.com/avatar/${hash}?d=identicon`);
    } else {
      setAvatarUrl("");
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-full max-w-sm bg-card rounded-2xl shadow-login-panel overflow-hidden p-0">
        {/* Blue Header Section */}
        <div className="bg-primary px-8 py-8 text-center">
          <div className="w-16 h-16 bg-white/20 rounded-full mx-auto mb-4 flex items-center justify-center overflow-hidden">
            {avatarUrl ? (
              <img src={avatarUrl} alt="Avatar" className="w-16 h-16 object-cover" />
            ) : (
              <User className="w-8 h-8 text-white" />
            )}
          </div>
          <DialogHeader className="sm:text-center">
            <DialogTitle className="text-2xl font-light text-white">{getTranslation(language, "createAccount")}</DialogTitle>
          </DialogHeader>
          <p className="text-white/80 mt-1 font-light">{getTranslation(language, "enterDetailsToSignup")}</p>
        </div>

        {/* White Content Section */}
        <div className="px-8 py-6 space-y-4">
          {/* First Name */}
          <div className="space-y-2">
            <Label htmlFor="firstName" className="text-sm font-medium">{getTranslation(language, "firstName")}</Label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                id="firstName"
                type="text"
                placeholder={getTranslation(language, "firstName")}
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                className="w-full bg-input border-border text-card-foreground placeholder:text-muted-foreground rounded h-10 pl-10 focus:border-primary focus:ring-primary/30 transition-all duration-200"
              />
            </div>
          </div>

          {/* Last Name */}
          <div className="space-y-2">
            <Label htmlFor="lastName" className="text-sm font-medium">{getTranslation(language, "lastName")}</Label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                id="lastName"
                type="text"
                placeholder={getTranslation(language, "lastName")}
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                className="w-full bg-input border-border text-card-foreground placeholder:text-muted-foreground rounded h-10 pl-10 focus:border-primary focus:ring-primary/30 transition-all duration-200"
              />
            </div>
          </div>

          {/* Email */}
          <div className="space-y-2">
            <Label htmlFor="email" className="text-sm font-medium">{getTranslation(language, "email")}</Label>
            <div className="relative">
              <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                id="email"
                type="email"
                placeholder={getTranslation(language, "emailAddress")}
                value={email}
                onChange={(e) => handleEmailChange(e.target.value)}
                className="w-full bg-input border-border text-card-foreground placeholder:text-muted-foreground rounded h-10 pl-10 focus:border-primary focus:ring-primary/30 transition-all duration-200"
              />
            </div>
          </div>

          {/* Password */}
          <div className="space-y-2">
            <Label htmlFor="password" className="text-sm font-medium">{getTranslation(language, "password")}</Label>
            <div className="relative">
              <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                id="password"
                type={showPassword ? "text" : "password"}
                placeholder={getTranslation(language, "password")}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full bg-input border-border text-card-foreground placeholder:text-muted-foreground rounded h-10 pl-10 pr-10 focus:border-primary focus:ring-primary/30 transition-all duration-200"
                onKeyDown={(e) => e.key === "Enter" && handleSignup()}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 transform -translate-y-1/2 text-muted-foreground hover:text-card-foreground transition-colors"
              >
                {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
          </div>
          <span className="text-xs text-muted-foreground">{getTranslation(language, "doubleCheckPassword")}</span>
          <Button
            onClick={handleSignup}
            disabled={!firstName || !lastName || !email || !password}
            className="w-full bg-primary hover:bg-primary-glow text-primary-foreground font-medium rounded h-10 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {getTranslation(language, "createAccount")}
          </Button>

          {/* <div className="mt-6 text-center space-x-4 text-xs text-muted-foreground">
            <button className="hover:underline">Privacy & cookies</button>
            <button className="hover:underline">Terms of use</button>
          </div> */}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default SignupModal;
