// 00.references/from.loginStandard/accessControl/authentication/loginStandard/options/temporaryKeyModal.tsx
import { useMemo, useState, useEffect, useCallback } from "react";
import { getTranslation, type LocaleCode } from "@/lib/i18n";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import QRCode from "react-qr-code";
import { Copy, ExternalLink, Eye, EyeOff, Archive, ArchiveX } from "lucide-react";
import { toast } from "sonner";
import { Importing } from "@/components/global";
import { Exporting } from "@/components/global/privateKeyManagement/exporting";
import { PrivateKeyExtraction } from "@/components/global/privateKeyManagement";
import {
  BitcoinAddressDisplay,
  LitecoinAddressDisplay,
  PolkadotAddressDisplay,
  MultiFormatAddressRenderer,
  generateMultiFormatAddresses,
  type StacksAddresses
} from '@/components/currencyCore/currencies/ext/multiFormatAddresses';
import type { DerivedInfo } from '@/components/currencyCore/currencies/currencyData';
import { QrCodeMultFormatAddressDisplay } from '@/components/partials/qrCode';
import { ImportGenerationStyle } from '@/components/currencyCore/currencies/ext';
// import { cardanoData, CardanoAddressFormat } from "@/components/currencyCore/currencies/ADA.Cardano"; // DISABLED
import { DomainRouter } from '@/components/currencyCore/domains/router.domains';
import { SupportedTicker, NETWORKS, PROTOCOL_PREFIXES } from '@/components/currencyCore/currencies';


interface TemporaryKeyModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  bruteForceMode?: boolean;
  onBruteForceModeChange?: (mode: boolean) => void;
  language?: LocaleCode;
}

import {
  BitcoinAddresses,
  LitecoinAddresses,
  StacksAddressDisplay
} from '@/components/currencyCore/currencies/ext/multiFormatAddresses';


// DISABLED: Cardano types and functionality
// type CardanoAddresses = {
//   BaseAddress?: { address: string; description: string };
//   ByronAddress?: { address: string; description: string };
//   RewardAddress?: { address: string; description: string };
// };


// Function to get block explorer link using currency-specific methods
const getBlockExplorerLink = async (ticker: string, format: string, address: string): Promise<string | null> => {
  try {
    // Import the currency data
    const { currencyByTicker } = await import('@/components/currencyCore/currencies');
    const currency = currencyByTicker[ticker];
    
    // All currencies now have their own getBlockExplorerLink method
    if (currency?.getBlockExplorerLink) {
      return currency.getBlockExplorerLink(address, format);
    }
    
    // No fallback needed - all currencies have been migrated
    console.warn(`Currency ${ticker} does not have a getBlockExplorerLink method`);
    return null;
  } catch (error) {
    console.error(`Error getting block explorer link for ${ticker}:`, error);
    return null;
  }
};

async function deriveFromPrivateKey(
  ticker: SupportedTicker, 
  priv: string,
  polkadotMethod?: 'auto' | 'polkadotjs' | 'exodus'
): Promise<DerivedInfo> {
  // Import the currency data
  const { currencyByTicker } = await import('@/components/currencyCore/currencies');
  
  // Get the currency data for the selected ticker
  const currency = currencyByTicker[ticker];
  
  // Check if the currency exists and has a derivation function
  if (!currency) {
    throw new Error(`Unsupported ticker: ${ticker}`);
  }
  
  if (!currency.deriveFromPrivateKey) {
    throw new Error(`No derivation function available for ${ticker}`);
  }
  
  // Use the currency-specific derivation function
  try {
    // For Polkadot, pass the selected method
    if (ticker === 'DOT' && polkadotMethod) {
      return await currency.deriveFromPrivateKey(priv, polkadotMethod);
    }
    
    return await currency.deriveFromPrivateKey(priv);
  } catch (error) {
    console.error(`Error deriving ${ticker} address:`, error);
    throw new Error(`Failed to derive ${ticker} address: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

export const TemporaryKeyModal = ({ open, onOpenChange, bruteForceMode, onBruteForceModeChange, language = "en" }: TemporaryKeyModalProps) => {
  const [ticker, setTicker] = useState<SupportedTicker>("ETH");
  const [privateKeyInput, setPrivateKeyInput] = useState("");
  const [processedPrivateKey, setProcessedPrivateKey] = useState<string>(""); // Store the actual private key used for derivation
  const [derived, setDerived] = useState<DerivedInfo | null>(null);
  const [bitcoinAddresses, setBitcoinAddresses] = useState<BitcoinAddresses | null>(null);
  const [litecoinAddresses, setLitecoinAddresses] = useState<LitecoinAddresses | null>(null);
  const [stacksAddresses, setStacksAddresses] = useState<StacksAddresses | null>(null);
  const [showPrivateKey, setShowPrivateKey] = useState(false);
  const [qrCodeAddress, setQrCodeAddress] = useState<string>("");
  const [selectedNetwork, setSelectedNetwork] = useState<string>("");
  const [showExportPanel, setShowExportPanel] = useState(false);
  const [polkadotImportMethod, setPolkadotImportMethod] = useState<'exodus' | 'polkadotjs' | 'auto'>('auto');
  // const [cardanoAddresses, setCardanoAddresses] = useState<CardanoAddresses | null>(null); // DISABLED

  const resetAll = () => {
    setTicker("ETH");
    setPrivateKeyInput("");
    setProcessedPrivateKey("");
    setDerived(null);
    setBitcoinAddresses(null);
    setLitecoinAddresses(null);
    setStacksAddresses(null);
    setShowPrivateKey(false);
    setQrCodeAddress("");
    setSelectedNetwork("");
    setShowExportPanel(false);
    setPolkadotImportMethod('auto');
    // setCardanoAddresses(null); // DISABLED
  };

  const handleAddressChange = (address: string, network: string) => {
    setQrCodeAddress(address);
    setSelectedNetwork(network);
  };

  const networkOption = useMemo(() => NETWORKS.find(n => n.ticker === ticker)!, [ticker]);

  // Re-derive address when Polkadot import method changes
  useEffect(() => {
    if (ticker === 'DOT' && derived && privateKeyInput) {
      console.log(`🔄 [TemporaryKeyModal] Polkadot method changed to: ${polkadotImportMethod}`);
      console.log(`🔄 [TemporaryKeyModal] Re-deriving address with new method...`);
      // Trigger re-derivation by calling handleDerive
      handleDerive();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [polkadotImportMethod]);





  const handleDerive = async () => {
    console.log("🎯 handleDerive called with ticker:", ticker, "privateKey length:", privateKeyInput.trim().length);
    console.log("🔑 privateKeyInput preview:", privateKeyInput.trim().substring(0, 100) + "...");

    const resolvedInput = privateKeyInput.trim();

    // Additional check for JSON content
    if (resolvedInput.startsWith('{"version"') || resolvedInput.includes('"crypto"')) {
      console.log("❌ ERROR: resolvedInput contains JSON keystore instead of private key!");
      console.log("🚨 This means the Importing component didn't properly handle the keystore");
      toast.error(getTranslation(language, "invalidPrivateKeyFormat"));
      return;
    }
    
    try {
      // Use the unified address generation service
      const result = await generateMultiFormatAddresses(
        ticker,
        resolvedInput,
        ticker === 'DOT' ? polkadotImportMethod : undefined
      );

      // Store the processed private key for export
      setProcessedPrivateKey(resolvedInput);

      // Update all state with the generated addresses
      setDerived(result.derived);
      setQrCodeAddress(result.derived.address);
      setBitcoinAddresses(result.bitcoinAddresses || null);
      setLitecoinAddresses(result.litecoinAddresses || null);
      setStacksAddresses(result.stacksAddresses || null);

      // Clear addresses for unsupported tickers
      if (!result.bitcoinAddresses && !result.litecoinAddresses && !result.stacksAddresses) {
        setBitcoinAddresses(null);
        setLitecoinAddresses(null);
        setStacksAddresses(null);
      }
    } catch (e) {
      console.error("❌ Error in handleDerive:", e);
      toast.error(`${getTranslation(language, "error")} ${e instanceof Error ? e.message : 'Unknown error'}`);
      setDerived(null);
      setQrCodeAddress("");
      setSelectedNetwork("");
      setBitcoinAddresses(null);
      setLitecoinAddresses(null);
      setStacksAddresses(null);
      // setCardanoAddresses(null); // DISABLED
      
      // If this is a Tezos or Polkadot error related to format, provide more guidance
      const errorMsg = e instanceof Error ? e.message : 'Unknown error';
      if (ticker === "XTZ" && errorMsg.includes("Tezos")) {
        toast(getTranslation(language, "tezosTip"), {
          description: getTranslation(language, "tezosTipDescription")
        });
      } else if (ticker === "DOT" && errorMsg.includes("Polkadot")) {
        toast(getTranslation(language, "polkadotTip"), {
          description: getTranslation(language, "polkadotTipDescription")
        });
      }
    }
  };

  const getExplorerLink = async (ticker: SupportedTicker, address: string) => {
    const { currencyByTicker } = await import('@/components/currencyCore/currencies');
    const currency = currencyByTicker[ticker];
    if (currency?.blockExplorer?.blockExplorerLink) {
      return `${currency.blockExplorer.blockExplorerLink}${address}`;
    }
    return null;
  };

  
  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text)
      .then(() => {
        toast.success(`${label} copied to clipboard`);
      })
      .catch((err) => {
        console.error('Failed to copy:', err);
        toast.error('Failed to copy to clipboard');
      });
  };

  return (
    <>
    <Dialog
      open={open}
      onOpenChange={(o) => {
        if (!o) {
          resetAll();
          onOpenChange(false);
        } else {
          onOpenChange(true);
        }
      }}
    >
      <DialogContent className={`w-full ${showExportPanel ? 'max-w-5xl' : 'max-w-2xl'} bg-card rounded-2xl shadow-login-panel overflow-hidden`}>
        <div className="px-6 py-4 relative">
          <button
            aria-label="Close"
            className="absolute right-3 top-3 inline-flex items-center justify-center h-8 w-8 rounded-full bg-transparent hover:bg-black/5 text-black/70 hover:text-black transition"
            onClick={() => { resetAll(); onOpenChange(false); }}
          >
            ✕
          </button>
          <DialogHeader>
            <DialogTitle className="text-xl text-black">{getTranslation(language, "temporaryPrivateKey")}</DialogTitle>
          </DialogHeader>
          <div className="mt-4 grid grid-cols-1 md:grid-cols-[125px_1fr] gap-4 items-end">
            <div>
              <Label className="mb-2 block text-black">{getTranslation(language, "network")}</Label>
              <Select value={ticker} onValueChange={(v) => {
                const newTicker = v as SupportedTicker;
                if (newTicker !== ticker) {
                  setTicker(newTicker);
                  setPrivateKeyInput("");
                  setProcessedPrivateKey("");
                  setDerived(null);
                  setQrCodeAddress("");
                  setSelectedNetwork("");
                  setBitcoinAddresses(null);
                  setLitecoinAddresses(null);
                  setPolkadotImportMethod('auto');
                  // setCardanoAddresses(null); // DISABLED
                }
              }}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder={getTranslation(language, "selectNetwork")} />
                </SelectTrigger>
                <SelectContent>
                  {NETWORKS.map((n) => (
                    <SelectItem key={n.ticker} value={n.ticker}>
                      <span className="inline-flex items-center gap-2">
                        <img src={n.icon} alt={n.ticker} className="w-4 h-4" />
                        {n.label}
                      </span>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <Importing
              label={`${networkOption.label} ${getTranslation(language, "privateKey")}`}
              placeholder={getTranslation(language, "pastePrivateKey")}
              value={privateKeyInput}
              onChange={setPrivateKeyInput}
              onSubmit={handleDerive}
              submitLabel={getTranslation(language, "use")}
              acceptedFileTypes=".json,.txt,.key"
              bruteForceMode={bruteForceMode}
              onBruteForceModeChange={onBruteForceModeChange}
              language={language}
            />
          </div>

          //TODO: Consider moving this to a separate component.2
          {/* Polkadot Import Method Toggle - Only shown when DOT is selected */}
          {ticker === "DOT" && (
            <div className="mt-4">
              <div className="flex items-center justify-start gap-3 px-1">
                <Label className="text-sm text-black font-medium">{getTranslation(language, "importMethod")}</Label>
                <ImportGenerationStyle
                  value={polkadotImportMethod}
                  onChange={setPolkadotImportMethod}
                />
              </div>
              {/* Show note if keystore was imported */}
              {privateKeyInput.startsWith('PKCS8_PUB:') && (
                <div className="mt-2 px-1 text-xs text-gray-600 dark:text-gray-400">
{getTranslation(language, "keystoreImportNote")}
                </div>
              )}
            </div>
          )}

          {derived && (
            <div className="mt-6 w-full">
              <div className={`flex ${showExportPanel ? 'flex-row' : 'flex-col'} items-start gap-6`}>
                {/* QR Code and Address Information */}
                <div className="flex flex-col items-center gap-3 flex-shrink-0">
                  <div className="relative">
                    <QRCode
                      value={qrCodeAddress || derived.address}
                      size={280}
                      level="H"
                      bgColor="white"
                      fgColor="black"
                    />
                    <div className="absolute inset-0 flex items-center justify-center">
                      <img
                        src={networkOption.icon}
                        alt={ticker}
                        className="w-16 h-16 bg-white rounded-full p-2 shadow-lg"
                      />
                    </div>
                  </div>

                  {/* Pill switcher for Polkadot, Litecoin, Bitcoin, and Stacks multi-format addresses */}
                  {(ticker === "DOT" || ticker === "LTC" || ticker === "BTC" || ticker === "STX") && derived.formattedDisplay && (
                    <QrCodeMultFormatAddressDisplay
                      formattedDisplay={derived.formattedDisplay}
                      onAddressChange={handleAddressChange}
                    />
                  )}
                  <div className="mt-4 text-xs break-all text-muted-foreground text-center w-full max-w-[520px] flex items-center justify-center gap-2">
                    <div className="flex-grow text-center">
                      {/* Handle Polkadot, Litecoin, Bitcoin, and Stacks multi-format display */}
                      {(ticker === "DOT" || ticker === "LTC" || ticker === "BTC" || ticker === "STX") && derived.formattedDisplay && selectedNetwork ? (
                        // Display only the selected network address
                        <a
                          href="#"
                          onClick={async (e) => {
                            e.preventDefault();
                            const link = await getExplorerLink(ticker, qrCodeAddress);
                            if (link) {
                              window.open(link, '_blank', 'noopener,noreferrer');
                            }
                          }}
                          className="text-blue-600 hover:text-blue-800 underline break-all block"
                        >
                          {selectedNetwork}://{qrCodeAddress}
                        </a>
                      ) : (ticker === "DOT" || ticker === "LTC" || ticker === "BTC" || ticker === "STX") && derived.formattedDisplay ? (
                        // Fallback: Display all networks/formats on separate lines (when no selection made yet)
                        <div className="space-y-1">
                          {derived.formattedDisplay.split('\n').map((line, index) => (
                            <div key={index}>
                              <a
                                href="#"
                                onClick={async (e) => {
                                  e.preventDefault();
                                  // Extract address from the line (remove protocol prefix)
                                  const address = line.replace(/^.*:\/\/(.*)$/, '$1');
                                  const link = await getExplorerLink(ticker, address);
                                  if (link) {
                                    window.open(link, '_blank', 'noopener,noreferrer');
                                  }
                                }}
                                className="text-blue-600 hover:text-blue-800 underline break-all block"
                              >
                                {line}
                              </a>
                            </div>
                          ))}
                        </div>
                      ) : (
                        /* Regular single network display */
                        <a
                          href="#"
                          onClick={async (e) => {
                            e.preventDefault();
                            const link = await getExplorerLink(ticker, derived.address);
                            if (link) {
                              window.open(link, '_blank', 'noopener,noreferrer');
                            }
                          }}
                          className="text-blue-600 hover:text-blue-800 underline break-all"
                        >
                          {`${PROTOCOL_PREFIXES[ticker]}${derived.address}`}
                        </a>
                      )}
                    </div>
                    <button
                      onClick={() => copyToClipboard(
                        (ticker === "DOT" || ticker === "LTC" || ticker === "BTC" || ticker === "STX") && derived.formattedDisplay && selectedNetwork
                          ? `${selectedNetwork}://${qrCodeAddress}` // Copy selected network/format address
                          : (ticker === "DOT" || ticker === "LTC" || ticker === "BTC" || ticker === "STX") && derived.formattedDisplay
                          ? derived.formattedDisplay // Copy all addresses when no selection made
                          : `${PROTOCOL_PREFIXES[ticker]}${derived.address}`, // Standard format for other currencies
getTranslation(language, "walletAddress")
                      )}
                      className="p-1 rounded hover:bg-gray-200 transition-colors"
                      title={getTranslation(language, "copyWalletAddress")}
                    >
                      <Copy size={16} />
                    </button>
                  </div>

                  {/* Domain Name Display - resolves automatically */}
                  <DomainRouter 
                    address={derived.address}
                    ticker={ticker}
                    copyToClipboard={copyToClipboard}
                    language={language}
                  />
                  
                  
                  {/* STX Private Key Display - using extracted component */}
                  <PrivateKeyExtraction
                    ticker={ticker}
                    derived={derived}
                    showPrivateKey={showPrivateKey}
                    setShowPrivateKey={setShowPrivateKey}
                    copyToClipboard={copyToClipboard}
                    language={language}
                  />

                  <div className="mt-2 text-xs break-all text-muted-foreground text-center w-full max-w-[520px] flex items-center justify-center gap-2">
                    <div className="flex-grow text-center">
                      <span className="break-all">
                        publicKey.{ticker}://{derived.publicKey}
                      </span>
                    </div>
                    <button
                      onClick={() => copyToClipboard(derived.publicKey, getTranslation(language, "publicKey"))}
                      className="p-1 rounded hover:bg-gray-200 transition-colors"
                      title={getTranslation(language, "copyPublicKey")}
                    >
                      <Copy size={16} />
                    </button>
                  </div>
                  
                  {/* Multi-format addresses display - unified component */}
                  <MultiFormatAddressRenderer
                    ticker={ticker}
                    derived={derived}
                    bitcoinAddresses={bitcoinAddresses}
                    litecoinAddresses={litecoinAddresses}
                    copyToClipboard={copyToClipboard}
                    getBlockExplorerLink={getBlockExplorerLink}
                  />

                </div>

                {/* Export Panel - shown when toggle is active */}
                {showExportPanel && (
                  <div className="flex-shrink-0 w-80">
                    <Exporting
                      privateKey={processedPrivateKey}
                      publicKey={derived.publicKey}
                      address={derived.address}
                      currency={ticker}
                      onClose={() => setShowExportPanel(false)}
                      language={language}
                    />
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Archive/Export Toggle Button - Bottom Right Corner */}
          {derived && (
            <button
              onClick={() => setShowExportPanel(!showExportPanel)}
              className={`absolute bottom-2 right-2 p-3 rounded-full transition-colors shadow-lg ${
                showExportPanel
                  ? 'bg-blue-100 text-blue-600 hover:bg-blue-200'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
              title={showExportPanel ? getTranslation(language, "hideExportOptions") : getTranslation(language, "showExportOptions")}
            >
              {showExportPanel ? <ArchiveX size={20} /> : <Archive size={20} />}
            </button>
          )}
        </div>
      </DialogContent>
    </Dialog>
    </>
  );
};

export default TemporaryKeyModal;

// src/components/modals/loginOptions/TemporaryKeyModal.vue
<template>
  <Teleport to="body">
    <Transition name="modal">
      <div v-if="isOpen" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" @click.self="closeModal">
        <div class="w-full max-w-2xl bg-blue-600 rounded-2xl shadow-xl overflow-hidden">
          <!-- Blue Header Section -->
          <div class="bg-blue-600 px-8 pt-16 pb-10 text-center rounded-t-2xl">
            <div class="w-16 h-16 bg-white/20 rounded-full mx-auto mt-4 mb-4 flex items-center justify-center">
              <Key :size="32" class="text-white" />
            </div>
            <h2 class="text-2xl font-light text-white">{{ t('temporaryPrivateKey') }}</h2>
            <p class="text-white/80 mt-1 font-light">Load a private key without logging in</p>
          </div>

          <!-- White Content Section -->
          <div class="px-8 pt-12 pb-8 space-y-4 bg-white">
            <!-- Network Selection and Private Key Input -->
            <div class="grid grid-cols-1 md:grid-cols-[125px_1fr] gap-4 items-end min-w-0">
              <!-- Network Selection (Custom Dropdown with Icons) -->
              <div class="relative pl-2" ref="networkDropdownRef">
                <label class="text-sm font-medium text-gray-700 pl-3 mb-2 block">{{ t('network') }}</label>
                <button
                  ref="networkButtonRef"
                  type="button"
                  @click="toggleNetworkDropdown"
                  class="w-full bg-gray-50 border border-gray-300 text-gray-900 rounded h-10 px-3 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/30 transition-all duration-200 outline-none flex items-center justify-between"
                >
                  <span class="flex items-center gap-2">
                    <img 
                      :src="getSelectedNetworkIcon()" 
                      :alt="selectedTicker" 
                      class="w-5 h-5"
                      @error="handleIconError"
                    />
                    <span>{{ getSelectedNetworkLabel() }}</span>
                  </span>
                  <ChevronDown :size="16" class="text-gray-400 transition-transform duration-200" :class="{ 'rotate-180': isNetworkDropdownOpen }" />
                </button>
              </div>
              
              <!-- Teleported Dropdown Options (outside modal to avoid overflow clipping) -->
              <Teleport to="body">
                <div 
                  v-if="isNetworkDropdownOpen"
                  ref="dropdownMenuRef"
                  class="fixed z-100 bg-white border border-gray-300 rounded-lg shadow-lg max-h-60 overflow-y-auto"
                  :style="dropdownStyle"
                >
                  <div
                    v-for="network in networks"
                    :key="network.ticker"
                    @click="selectNetwork(network.ticker)"
                    class="flex items-center gap-2 px-3 py-2 hover:bg-blue-50 cursor-pointer transition-colors"
                    :class="{ 'bg-blue-100': network.ticker === selectedTicker }"
                  >
                    <img 
                      :src="network.icon" 
                      :alt="network.ticker" 
                      class="w-5 h-5"
                      @error="handleIconError"
                    />
                    <span class="text-gray-900">{{ network.label }}</span>
                  </div>
                </div>
              </Teleport>

              <!-- Private Key Input -->
              <div class="min-w-0">
                <label class="text-sm font-medium text-gray-700 pl-3 mb-2 block">
                  {{ getNetworkLabel() }} {{ t('privateKey') }}
                </label>
                <div class="flex items-end gap-2 pr-4">
                  <div class="relative flex-1 min-w-0">
                    <Key :size="16" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 pointer-events-none" />
                    <input
                      v-model="privateKeyInput"
                      type="text"
                      :placeholder="t('pastePrivateKey')"
                      style="padding-left: 2.5rem; padding-right: 3rem; max-width: 435px;"
                      class="w-full bg-gray-50 border border-gray-300 text-gray-900 placeholder:text-gray-400 rounded h-10 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/30 transition-all duration-200 outline-none"
                    />
                    <input
                      ref="fileInputRef"
                      type="file"
                      accept=".json,.txt,.key,.csv"
                      class="hidden"
                      @change="handleFileImport"
                    />
                    <button
                      @click="triggerFileInput"
                      class="absolute right-1 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                      type="button"
                    >
                      <FileUp :size="16" />
                    </button>
                  </div>
                  <!-- Derive Button -->
                  <button
                    @click="handleDerive"
                    :disabled="!privateKeyInput.trim()"
                    style="background-color: #2563eb;"
                    class="px-3 hover:bg-blue-700 text-white text-sm font-medium rounded h-10 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap"
                  >
                    {{ t('use') }}
                  </button>
                </div>
              </div>
            </div>

            <!-- Results Section -->
            <div v-if="derivedAddress" class="space-y-4" style="margin-top: 15px;">
              <!-- QR Code -->
              <div class="flex justify-center" style="padding-top: 2px;">
                <div class="relative">
                  <QrcodeVue
                    :value="derivedAddress"
                    :size="280"
                    level="H"
                    render-as="svg"
                    background="#ffffff"
                    foreground="#000000"
                  />
                  <div class="absolute inset-0 flex items-center justify-center pointer-events-none">
                    <img
                      :src="getSelectedNetworkIcon()"
                      :alt="selectedTicker"
                      class="w-16 h-16 bg-white rounded-full p-2 shadow-lg"
                    />
                  </div>
                </div>
              </div>

              <!-- Address Display -->
              <div class="space-y-2">
                <label class="text-sm font-medium text-gray-700 pl-3 block">{{ t('walletAddress') }}</label>
                <div class="flex items-center gap-2 p-3 bg-gray-50 rounded-md">
                  <span class="flex-1 text-sm font-mono break-all">{{ derivedAddress }}</span>
                  <button
                    @click="copyToClipboard(derivedAddress, t('walletAddress'))"
                    class="p-1 text-gray-400 hover:text-gray-600 transition-colors"
                  >
                    <Copy :size="16" />
                  </button>
                </div>
              </div>

              <!-- Public Key Display -->
              <div v-if="derivedPublicKey" class="space-y-2">
                <label class="text-sm font-medium text-gray-700 pl-3 block">{{ t('publicKey') }}</label>
                <div class="flex items-center gap-2 p-3 bg-gray-50 rounded-md">
                  <span class="flex-1 text-sm font-mono break-all">{{ derivedPublicKey }}</span>
                  <button
                    @click="copyToClipboard(derivedPublicKey, t('publicKey'))"
                    class="p-1 text-gray-400 hover:text-gray-600 transition-colors"
                  >
                    <Copy :size="16" />
                  </button>
                </div>
              </div>

              <!-- Block Explorer Link -->
              <div v-if="blockExplorerLink" class="space-y-2">
                <label class="text-sm font-medium text-gray-700 pl-3 block">{{ t('viewOnExplorer') }}</label>
                <a
                  :href="blockExplorerLink"
                  target="_blank"
                  rel="noopener noreferrer"
                  class="inline-flex items-center gap-2 text-blue-600 hover:text-blue-800 transition-colors ml-3"
                >
                  <ExternalLink :size="16" />
                  {{ t('openInExplorer') }}
                </a>
              </div>
            </div>

            <!-- Error Message -->
            <div v-if="errorMessage" class="p-3 bg-red-50 border border-red-200 rounded-md">
              <p class="text-sm text-red-600">{{ errorMessage }}</p>
            </div>

            <!-- Footer Spacer -->
            <div class="mt-6 h-8"></div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { Key, Eye, EyeOff, Copy, ExternalLink, ChevronDown, FileUp } from 'lucide-vue-next'
import { useI18n } from '@/composables/useI18n'
import QrcodeVue from 'qrcode.vue'
// Import only types from currencyData.ts (doesn't load heavy currency modules)
import type { CurrencyData } from '@/lib/currencyCore/currencies/currencyData'

// Type for supported cryptocurrency tickers (matches currencies/index.ts)
type SupportedTicker = "ALGO" | "AR" | "ATOM" | "BCH" | "BNB" | "BTC" | "DOGE" | "DOT" | "ETC" | "ETH" | "LTC" | "LUNA" | "LUNC" | "SOL" | "STX" | "TRX" | "WAVES" | "XLM" | "XRP" | "XTZ"

// Network type for display
interface NetworkInfo {
  ticker: SupportedTicker
  label: string
  icon: string
}

// Static NETWORKS data (mirroring currencies/index.ts to avoid heavy imports at startup)
const STATIC_NETWORKS: NetworkInfo[] = [
  { ticker: "ALGO", label: "ALGO://", icon: "/assets/icons/crypto/algo.svg" },
  { ticker: "AR", label: "AR://", icon: "/assets/icons/crypto/ar.svg" },
  { ticker: "ATOM", label: "ATOM://", icon: "/assets/icons/crypto/atom.svg" },
  { ticker: "BCH", label: "BCH://", icon: "/assets/icons/crypto/bch.svg" },
  { ticker: "BNB", label: "BNB://", icon: "/assets/icons/crypto/bnb.svg" },
  { ticker: "BTC", label: "BTC://", icon: "/assets/icons/crypto/btc.svg" },
  { ticker: "DOGE", label: "DOGE://", icon: "/assets/icons/crypto/doge.svg" },
  { ticker: "DOT", label: "DOT://", icon: "/assets/icons/crypto/dot.svg" },
  { ticker: "ETC", label: "ETC://", icon: "/assets/icons/crypto/etc.svg" },
  { ticker: "ETH", label: "ETH://", icon: "/assets/icons/crypto/eth.svg" },
  { ticker: "LTC", label: "LTC://", icon: "/assets/icons/crypto/ltc.svg" },
  { ticker: "LUNA", label: "LUNA://", icon: "/assets/icons/crypto/luna.svg" },
  { ticker: "LUNC", label: "LUNC://", icon: "/assets/icons/crypto/lunc.svg" },
  { ticker: "SOL", label: "SOL://", icon: "/assets/icons/crypto/sol.svg" },
  { ticker: "STX", label: "STX://", icon: "/assets/icons/crypto/stx.svg" },
  { ticker: "TRX", label: "TRX://", icon: "/assets/icons/crypto/trx.svg" },
  { ticker: "WAVES", label: "WAVES://", icon: "/assets/icons/crypto/waves.svg" },
  { ticker: "XLM", label: "XLM://", icon: "/assets/icons/crypto/xlm.svg" },
  { ticker: "XRP", label: "XRP://", icon: "/assets/icons/crypto/xrp.svg" },
  { ticker: "XTZ", label: "XTZ://", icon: "/assets/icons/crypto/xtz.svg" },
]

interface TemporaryKeyModalProps {
  isOpen: boolean
}

const props = defineProps<TemporaryKeyModalProps>()
const emit = defineEmits<{
  'update:open': [value: boolean]
  derive: [ticker: string, privateKey: string]
}>()

const { t } = useI18n()

const selectedTicker = ref<SupportedTicker>('ETH')
const privateKeyInput = ref('')
const showPrivateKey = ref(false)
const derivedAddress = ref('')
const derivedPublicKey = ref('')
const blockExplorerLink = ref('')
const errorMessage = ref('')

// Lazy-loaded currency data (loaded when modal opens)
const currencyByTicker = ref<Record<string, CurrencyData>>({})
// Pre-populate networks with static data so dropdown is available immediately
const networks = ref<NetworkInfo[]>(STATIC_NETWORKS)

// Custom dropdown state
const networkDropdownRef = ref<HTMLElement | null>(null)
const networkButtonRef = ref<HTMLElement | null>(null)
const dropdownMenuRef = ref<HTMLElement | null>(null)
const isNetworkDropdownOpen = ref(false)
const dropdownPosition = ref({ top: 0, left: 0, width: 0 })

// File import
const fileInputRef = ref<HTMLInputElement | null>(null)

const triggerFileInput = () => {
  fileInputRef.value?.click()
}

const handleFileImport = async (event: Event) => {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  
  if (!file) return
  
  try {
    const text = await file.text()
    
    // Try to parse as JSON first (for keystore files)
    try {
      const json = JSON.parse(text)
      
      // Check if it's an Ethereum-style keystore
      if (json.crypto || json.Crypto) {
        errorMessage.value = 'Keystore files require password decryption. Please extract the private key first.'
        return
      }
      
      // Check for common private key fields in JSON
      if (json.privateKey) {
        privateKeyInput.value = json.privateKey
      } else if (json.private_key) {
        privateKeyInput.value = json.private_key
      } else if (json.key) {
        privateKeyInput.value = json.key
      } else {
        errorMessage.value = 'Could not find private key in JSON file'
      }
    } catch {
      // Not JSON, treat as plain text private key
      privateKeyInput.value = text.trim()
    }
    
    // Clear the file input so the same file can be selected again
    target.value = ''
  } catch (error) {
    console.error('Error reading file:', error)
    errorMessage.value = 'Failed to read file'
  }
}

const updateDropdownPosition = () => {
  if (networkButtonRef.value) {
    const rect = networkButtonRef.value.getBoundingClientRect()
    dropdownPosition.value = {
      top: rect.bottom + 4, // 4px gap below button
      left: rect.left,
      width: rect.width
    }
  }
}

const toggleNetworkDropdown = () => {
  if (!isNetworkDropdownOpen.value) {
    updateDropdownPosition()
  }
  isNetworkDropdownOpen.value = !isNetworkDropdownOpen.value
}

const selectNetwork = (ticker: SupportedTicker) => {
  selectedTicker.value = ticker
  isNetworkDropdownOpen.value = false
}

const dropdownStyle = computed(() => ({
  top: `${dropdownPosition.value.top}px`,
  left: `${dropdownPosition.value.left}px`,
  minWidth: `${Math.max(dropdownPosition.value.width, 140)}px`
}))

const getSelectedNetworkIcon = () => {
  const network = networks.value.find(n => n.ticker === selectedTicker.value)
  return network?.icon || `/assets/icons/crypto/${selectedTicker.value.toLowerCase()}.svg`
}

const getSelectedNetworkLabel = () => {
  const network = networks.value.find(n => n.ticker === selectedTicker.value)
  return network?.label || `${selectedTicker.value}://`
}

const handleIconError = (event: Event) => {
  const target = event.target as HTMLImageElement
  target.style.opacity = '0.3'
}

// Close dropdown when clicking outside
const handleClickOutside = (event: MouseEvent) => {
  const target = event.target as Node
  const isInsideDropdownRef = networkDropdownRef.value?.contains(target)
  const isInsideDropdownMenu = dropdownMenuRef.value?.contains(target)
  
  if (!isInsideDropdownRef && !isInsideDropdownMenu) {
    isNetworkDropdownOpen.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
const currenciesLoaded = ref(false)
const currenciesLoading = ref(false)

// Load currencies dynamically when the modal opens (following reference pattern from temporaryKeyModal.tsx)
const loadCurrencies = async () => {
  if (currenciesLoaded.value || currenciesLoading.value) return
  
  currenciesLoading.value = true
  try {
    // Dynamic import for currencyByTicker to avoid loading heavy modules at startup
    const module = await import('@/lib/currencyCore/currencies')
    currencyByTicker.value = module.currencyByTicker
    networks.value = module.NETWORKS
    currenciesLoaded.value = true
  } catch (error) {
    console.error('Failed to load currencies:', error)
  } finally {
    currenciesLoading.value = false
  }
}

// Watch for modal open to load currencies
watch(() => props.isOpen, (isOpen) => {
  if (isOpen && !currenciesLoaded.value) {
    loadCurrencies()
  }
}, { immediate: true })

// Get all available networks from the currency data
// Filter to only include currencies that have deriveFromPrivateKey function
const availableNetworks = computed(() => {
  if (!currenciesLoaded.value) {
    // Return just ETH while loading
    return ['ETH'] as SupportedTicker[]
  }
  return Object.keys(currencyByTicker.value)
    .filter(ticker => currencyByTicker.value[ticker]?.deriveFromPrivateKey)
    .sort() as SupportedTicker[]
})

const getNetworkLabel = () => {
  // First check the loaded currency data
  const currency = currencyByTicker.value[selectedTicker.value]
  if (currency?.basicInfo?.name) return currency.basicInfo.name
  
  // Fallback to networks data
  const network = networks.value.find(n => n.ticker === selectedTicker.value)
  return network?.label?.replace('://', '') || selectedTicker.value
}

const getBlockExplorerUrl = async (ticker: string, address: string): Promise<string> => {
  // Dynamic import for getting block explorer (following reference pattern)
  try {
    const { currencyByTicker: currencies } = await import('@/lib/currencyCore/currencies')
    const currency = currencies[ticker]
    
    if (currency?.getBlockExplorerLink) {
      return currency.getBlockExplorerLink(address) || ''
    }
    
    // Fallback to blockExplorerLink if available
    if (currency?.blockExplorer?.blockExplorerLink) {
      return `${currency.blockExplorer.blockExplorerLink}${address}`
    }
  } catch (error) {
    console.error(`Error getting block explorer link for ${ticker}:`, error)
  }
  
  return ''
}

const handleDerive = async () => {
  if (!privateKeyInput.value.trim()) return

  errorMessage.value = ''
  derivedAddress.value = ''
  derivedPublicKey.value = ''
  blockExplorerLink.value = ''

  try {
    const resolvedInput = privateKeyInput.value.trim()
    
    // Check for JSON keystore content
    if (resolvedInput.startsWith('{"version"') || resolvedInput.includes('"crypto"')) {
      throw new Error('Keystore files require decryption. Please extract the private key first.')
    }
    
    // Use the unified address generation service (following reference pattern)
    const { generateMultiFormatAddresses } = await import('@/lib/currencyCore/currencies/ext/multiFormatAddresses')
    
    const result = await generateMultiFormatAddresses(
      selectedTicker.value,
      resolvedInput
    )
    
    if (!result || !result.derived || !result.derived.address) {
      throw new Error('Failed to derive address from private key')
    }

    derivedAddress.value = result.derived.address
    derivedPublicKey.value = result.derived.publicKey || ''
    
    // Get block explorer link
    const explorerUrl = await getBlockExplorerUrl(selectedTicker.value, result.derived.address)
    blockExplorerLink.value = explorerUrl
    
    emit('derive', selectedTicker.value, privateKeyInput.value.trim())
  } catch (error) {
    console.error('Derivation error:', error)
    errorMessage.value = error instanceof Error ? error.message : 'Failed to derive address'
  }
}

const copyToClipboard = async (text: string, label: string) => {
  try {
    await navigator.clipboard.writeText(text)
    // You could add a toast notification here
    console.log(`${label} copied to clipboard`)
  } catch (err) {
    console.error('Failed to copy:', err)
  }
}

const toggleShowPrivateKey = () => {
  showPrivateKey.value = !showPrivateKey.value
}

const closeModal = () => {
  emit('update:open', false)
  selectedTicker.value = 'ETH'
  privateKeyInput.value = ''
  showPrivateKey.value = false
  derivedAddress.value = ''
  derivedPublicKey.value = ''
  blockExplorerLink.value = ''
  errorMessage.value = ''
}


// Reset form when ticker changes
watch(selectedTicker, () => {
  privateKeyInput.value = ''
  derivedAddress.value = ''
  derivedPublicKey.value = ''
  blockExplorerLink.value = ''
  errorMessage.value = ''
})
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.3s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}

/* Chevron rotation transition */
.rotate-180 {
  transform: rotate(180deg);
}

svg {
  transition: transform 0.2s ease;
}
</style>
